# What is PyTorch?

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

## Getting Started

### Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
from __future__ import print_function
import torch

**Note**
    An uninitialized matrix is declared,
    but does not contain definite known
    values before it is used. When an
    uninitialized matrix is created,
    whatever values were in the allocated
    memory at the time will appear as the initial values.

Construct a 5x3 matrix, uninitialized:


In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[1.7672e+28, 1.2140e-38, 1.0739e-35],
        [4.4661e+24, 1.6503e+25, 1.0721e-35],
        [7.1459e+25, 2.6405e+26, 6.5203e-39],
        [4.8375e-20, 4.8281e-20, 1.1333e+27],
        [3.0897e-36, 6.5595e-39, 1.9350e-19]])


Construct a randomly initialized matrix:

In [3]:
x = torch.rand(5, 3)
x

tensor([[0.8633, 0.1098, 0.2742],
        [0.5353, 0.6271, 0.4863],
        [0.7739, 0.1399, 0.4711],
        [0.6387, 0.8280, 0.3086],
        [0.2265, 0.5183, 0.8815]])

Construct a matrix filled zeros and of dtype long:

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:

In [5]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.3388,  1.2755, -1.1636],
        [ 0.1136, -1.0224, -0.4732],
        [ 0.7995,  0.8060,  0.6007],
        [ 0.0204, -1.1574, -0.8736],
        [-0.1703,  1.1719,  0.0160]])


Get its size

`torch.Size` is in fact a tuple, so it supports all tuple operations.

In [7]:
print(x.size())

torch.Size([5, 3])


### Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Any operation that mutates a tensor in-place is post-fixed with an `_`.
For example: `x.copy_(y)`, `x.t_()`, will change `x`.

In [8]:
# Addition: syntax 1
y = torch.rand(5, 3)
print(x + y)

###############################################################
# Addition: syntax 2

print(torch.add(x, y))

###############################################################
# Addition: providing an output tensor as argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

###############################################################
# Addition: in-place

# adds x to y
y.add_(x)
print(y)

tensor([[ 1.3757,  1.4235, -0.7250],
        [ 0.5933, -0.7079,  0.2315],
        [ 0.8371,  1.3953,  1.2912],
        [ 0.0963, -0.8867, -0.0539],
        [ 0.0536,  1.4717,  0.7079]])
tensor([[ 1.3757,  1.4235, -0.7250],
        [ 0.5933, -0.7079,  0.2315],
        [ 0.8371,  1.3953,  1.2912],
        [ 0.0963, -0.8867, -0.0539],
        [ 0.0536,  1.4717,  0.7079]])
tensor([[ 1.3757,  1.4235, -0.7250],
        [ 0.5933, -0.7079,  0.2315],
        [ 0.8371,  1.3953,  1.2912],
        [ 0.0963, -0.8867, -0.0539],
        [ 0.0536,  1.4717,  0.7079]])
tensor([[ 1.3757,  1.4235, -0.7250],
        [ 0.5933, -0.7079,  0.2315],
        [ 0.8371,  1.3953,  1.2912],
        [ 0.0963, -0.8867, -0.0539],
        [ 0.0536,  1.4717,  0.7079]])


In [9]:
# You can use standard NumPy-like indexing with all bells and whistles!

print(x[:, 1])

tensor([ 1.2755, -1.0224,  0.8060, -1.1574,  1.1719])


In [10]:
# Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [11]:
# If you have a one element tensor, use ``.item()`` to get the value as a
# Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.3417])
-0.3417128920555115


A note to read later:

100+ Tensor operations, including transposing, indexing, slicing,
mathematical operations, linear algebra, random numbers, etc.,
are described [here](https://pytorch.org/docs/torch)

## NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

### Converting a Torch Tensor to a NumPy Array

In [12]:
a = torch.ones(5)
print(a)

###############################################################
#

b = a.numpy()
print(b)

###############################################################
# See how the numpy array changed in value.

a.add_(1)
print(a)
print(b)


tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting NumPy Array to Torch Tensor
See how changing the np array changed the Torch Tensor automatically

In [13]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

## CUDA Tensors

Tensors can be moved onto any device using the ``.to`` method.

Let us run this cell only if CUDA is available
We will use ``torch.device`` objects to move tensors in and out of GPU

In [14]:
if torch.cuda.is_available():
    print('CUDA is available!')
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!


CUDA is available!
tensor([0.6583], device='cuda:0')
tensor([0.6583], dtype=torch.float64)
